### ISSUE TITLE
✨[Feature] : To create a new model for Virtual Tour Guide feature of ARrow

### ISSUE THREAD

**Issue by vishal10kesharwani** [UBA-GCOEN/ARrow#8]
### Is there an existing issue raised for this?

- [x] I have searched the existing issues

### Describe the feature

> Design a visually appealing and accurate 3D model that captures the essence of the location.
> Incorporate interactive elements, such as clickable points of interest or hotspots, to provide users with relevant information.
> Ensure smooth navigation and user-friendly controls to allow users to explore different angles and viewpoints.
> Integrate the 3D model seamlessly into the tour guide feature, allowing users to access it during guided tours.

### Add Screenshots

None

### Record Options

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by vishal10kesharwani** [comment]
https://app.spline.design/file/57213438-cd37-483c-b9fe-8c0e200eb5e0 
Feature update , 3D Model Developement initiated.

**Comment by Siddhant-Patil0203** [comment]
@vishal10kesharwani to start with its okay

but need to improve it a lot
with certain iteration, it will get better
keep trying
Animation is cool and funny 👍

**Comment by Siddhant-Patil0203** [comment]
Hey @vishal10kesharwani 

I liked this one, Great job 🚀 
Go ahead with this one and make it more cooler

![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/969360b6-a125-454f-99a5-633fd2c0bf85)

**Comment by vishal10kesharwani** [comment]
Sçene 2 Updated , house model is taken only for as a reference, it'll be replaced by college model. @Siddhant-Patil0203 Need suggestions for the buttons if required to put inside 3d model.

**Comment by Siddhant-Patil0203** [comment]
@vishal10kesharwani 
Do you mean on the Mascot ??

**Comment by vishal10kesharwani** [comment]
Yes, along with model

**Comment by Siddhant-Patil0203** [comment]
No, I don't think we have to button on the mascot, but we have to put onhover or onclick animation on the model
@vishal10kesharwani

**Comment by Siddhant-Patil0203** [comment]
@LadeHarshal 
Have a look at the mascot and give your feedback according to your design

**Comment by vishal10kesharwani** [comment]
Sure, I'll make changes accordingly.

**Comment by LadeHarshal** [comment]
Looks good , goes well with colors used. Just that Logo on the bots front will standout more if instead of white bg we use the face color of the bot. @vishal10kesharwani What say?

**Comment by vishal10kesharwani** [comment]
@Siddhant-Patil0203 , animation added on various events like click on hands, click on model, hover on head, hover on body below head,

**Comment by vishal10kesharwani** [comment]
> Looks good , goes well with colors used. Just that Logo on the bots front will standout more if instead of white bg we use the face color of the bot. @vishal10kesharwani What say?
> 
Thanks for your suggestion @LadeHarshal , I'll try once with your considerations.

**Comment by Siddhant-Patil0203** [comment]
> @Siddhant-Patil0203 , animation added on various events like click on hands, click on model, hover on head, hover on body below head,

@vishal10kesharwani 
add a video demonstrating it, I am not able to see the animation properly on spline

**Comment by vishal10kesharwani** [comment]
https://github.com/UBA-GCOEN/ARrow/assets/66909545/51a2db89-c22f-4aa3-b656-6f053c748ea1

**Comment by Siddhant-Patil0203** [comment]
@vishal10kesharwani 
Head Animation is good 👍
But on mascot click and hands click and hover needs to be refined 
also, add sound to your animations

**Comment by vishal10kesharwani** [comment]
> @vishal10kesharwani 
> Head Animation is good 👍
> But on mascot click and hands click and hover needs to be refined 
> also, add sound to your animations
> 

Searching for sound that will look compatible to model

**Comment by vishal10kesharwani** [comment]
@Siddhant-Patil0203, Model Animations refined, Added Sounds on all animation events

**Comment by Siddhant-Patil0203** [comment]
@vishal10kesharwani 
The sounds are cool 🎶

Few things to do and then we will finalize the mascot : 
1. Add sound, when the bot moves 
2. We will only keep two animations, that is 
             a. onClick on the body ( apart from the head)
             b. onClick on head 
3. Keep the head sound the same, and for the body use the sound which you are currently using for onClick on hands
4. Remove all hover animation as hovers will not work well on androids. (so onHover eyes change should be onClick resp. for both animations)

animations refining :
1. onClick on the head, the star line above the bots head becomes straight, and the color of the star changes to red from gold, and the bot shakes his head a little in an angry mood 😡🤬, also we have to try a thing, that we have to change its eye color to red or keep it same, so make a different scene were the eye color changes to red onClick on the head and another scene where it remains same/don't change.

2. onClick on the body (apart from the head), the star line above the bot's head becomes straight, and the color of the star shines brighter 🌟 than the original gold ⭐, showing happiness and shinning gold stars, and the bots waves 👋 his hands, and his eyes twinkle (instead of 😌 this, it should be 🤩, figure it out how will you do that, make his circle eyes rotate once or any other thing figure it out yourself ) and for the eyes colors do it as told in point 1, two scene, one with no color change of eye and others with a change in the color of his eyes to gold while twinkling

3. Also make a diff. the scenes where his mouth shape changes according to onClick on the head and onClick on the body, you will have to make two scenes for change in the mouth, one with eye color and the other with no eye color change.

If you have any queries, pls. pin me

**Comment by vishal10kesharwani** [comment]
😯🫡

**Comment by vishal10kesharwani** [comment]
@Siddhant-Patil0203 , All suggested changes updated in model. Eyes animation will be refined on realtime implementation.

**Comment by Siddhant-Patil0203** [comment]
the animation is on hold not on click 
also don't change the face screen to red only change the eyes color
Movement sound is not good, it needs to be changed
click on the body animation of the eye is very bad, change it.
Also, Follow the point 2 properly 👇
>  for the eyes colors do it as told in point 1, two scene, one with no color change of eye and others with a change in the color of his eyes to gold while twinkling

And why haven't you made different scene as I told you to do so 👇 
> also we have to try a thing, that we have to change its eye color to red or keep it same, so make a different scene were the eye color changes to red onClick on the head and another scene where it remains same/don't change.

**Comment by vishal10kesharwani** [comment]
Referring to last point , transition from scenes would take transition delay that we can change and transition from states are customizable. .

**Comment by Siddhant-Patil0203** [comment]
Alright

**Comment by vishal10kesharwani** [comment]
@Siddhant-Patil0203 , now check sound of movement and recently listed  issues fix

**Comment by Siddhant-Patil0203** [comment]
Hey @vishal10kesharwani 
Use this eye expression on body touch (^ ^) or 😊

**Comment by vishal10kesharwani** [comment]
@Siddhant-Patil0203 ,Model Updated with Head Shake animation , eyes expression on body touch with moving sound

**Comment by vishal10kesharwani** [comment]
@Siddhant-Patil0203 ,Model Updated with Head Shake animation , eyes expression on body touch with moving sound

**Comment by Siddhant-Patil0203** [comment]
@vishal10kesharwani 
Make eye expression to ^ ^ instead of this - - 
I am talking about this expression 
![image](https://github.com/UBA-GCOEN/ARrow/assets/77800620/1affd0e2-0d81-45db-838e-464ef568bb8e)

rest all is good

**Comment by Siddhant-Patil0203** [comment]
Hey @vishal10kesharwani 
What's the status of the bot, 
Also,
Please add a PR of the bot spline preview link in the readme file 
and some Ss of the bot expression or a video.

**Comment by Siddhant-Patil0203** [comment]
Link this issue to the PR you will make
